---
# defaults file for slapd
slapd_hashing_algo: "SSHA"

slapd_root_dn: cn=admin,cn=config
slapd_root_pw: test

slapd_protocols: ldapi:/// ldap:///

#SSL Section
slapd_ssl: true
slapd_ssl_cert_path: /etc/ssl/certs/slapd.pem
slapd_ssl_cert_key_path: "{{ slapd_config_path }}slapd.key"
slapd_ssl_cert_ca_path:
slapd_ssl_cipher: NONE:+VERS-TLS1.2:+VERS-TLS1.1:+VERS-TLS1.0:+ECDHE-RSA:+DHE-RSA:+RSA:+AES-128-GCM:+AES-128-CBC:+AES-256-CBC:+SIGN-RSA-SHA256:+SIGN-RSA-SHA384:+SIGN-RSA-SHA512:+SIGN-RSA-SHA224:+SIGN-RSA-SHA1:+SIGN-DSA-SHA256:+SIGN-DSA-SHA224:+SIGN-DSA-SHA1:+CURVE-ALL:+AEAD:+SHA256:+SHA384:+SHA1:+COMP-NULL

#Self Signed Certificate#
slapd_ssl_self_signed: true
slapd_ssl_self_signed_renew: false
slapd_ssl_cert_key_length: 4096
slapd_ssl_cert_duration: 365
slapd_ssl_cert_country: AU
slapd_ssl_cert_state: Some-State
slapd_ssl_cert_location: Some-Locality
slapd_ssl_cert_organization: Internet Widgits Pty Ltd
slapd_ssl_cert_common_name: "{{ ansible_hostname }}"
